[general]
listen_addr = "0.0.0.0:3535"
pipe_file = "pipe.fifo"
log_json = false
log_debug = true

# The path to the secret file used for basic auth
basic_auth_secret_path = "/tmp/basic_auth_secret"

[actions]
# reboot = "reboot"
# rbuilder_restart = "/etc/init.d/rbuilder restart"
# rbuilder_stop = "/etc/init.d/rbuilder stop"
echo_test = "echo test"

[file_uploads]
testfile = "/tmp/testfile.txt"
